### PR TITLE
Modify _send_message to turn body into bytes for proper concatenation…

### LINKED ISSUE #14: TSaslClientTransport._send_message cannot concat str to bytes
When connecting to Hive through Impyla with mechanism 'GSSAPI' the `_send_message` method fails when trying to concatenate the string 'GSSAPI' to the header bytes. The solution for this (widely spread across the web) is to insert a type check and conversion for the `body`  argument as follows:

```
  def _send_message(self, status, body):
    header = struct.pack(">BI", status, len(body))
    if isinstance(body, str):
        body = body.encode()
    self._trans.write(header + body)
    self._trans.flush()
```
It would seem based on the `__init__` docstring that the expected behavior is to accept strings for the `mechanism` argument.  However, I'm not exactly sure how this is intended to work without converting to bytes when it is passed to `_send_message`. 

We would like to use thrift_sasl in a production system, but would rather rely on the cloudera distribution than an internally maintained distribution for just 2 lines of code. Would it be possible to include this change in any upcoming releases?

### PR DESCRIPTION
**Pull request by adamjsawicki**
… with header.

Implements the type check proposed in #14.

### CODE REVIEW

**Review by devinstevenson — APPROVED** [review]
Looks good, thanks for making the change.

**Comment by andrecowie** [comment]
Can someone get this merged in and a new version?

**Comment by flolas** [comment]
This PR still not in pip repository!  @timarmstrong when will be released in pip?

Thank you very much!

**Comment by dknupp** [comment]
Thanks for the comment @flolas -- the PR you're referring to broke compatibility with python 2.x. PR #19 addresses that so the code is cross-compatible.

**Pull request merged**
