### PR TITLE
Update to use Apache Thrift everywhere, instead of using thriftpy on Python 3.

### PR DESCRIPTION
**Pull request by matthewwardrop**
As requested by @wesm on a PR to impyla: https://github.com/cloudera/impyla/pull/251, here is an update to use Apache thrift everywhere.

Fully tested downstream in `pyhive` unit tests.

### CODE REVIEW

**Comment by matthewwardrop** [comment]
Hi @wesm. Merging this in now... But can you organise a release? Or set up travis auto-releasing? Or add me as a maintainer on PyPI?

**Comment by matthewwardrop** [comment]
@wesm Ping!

**Comment by wesm** [comment]
I just made you an owner on PyPI. Sorry for the delay!

**Comment by matthewwardrop** [comment]
Thanks @wesm, and no worries :).

**Pull request merged**
